### ISSUE TITLE
Excuse my ignorance, but...

### ISSUE THREAD

**Issue by GitLang** [nickzman/microcosm#1]
How on earth do I compile this wonderful pieve if work please?. I see nothing I recognise as any form of project file or makefile. Thanks. And thanks for Microcosm, even more gobsmacking on todays equipment as it was long ago.

**Comment by nickzman** [comment]
The project file is Microcosm.xcodeproj. Note that it might not build as-is with a modern version of Xcode unless you modify the project, because the original project targets the i386 architecture, which is no longer supported by Xcode 10 & later.

**Comment by GitLang** [comment]
Many thanks. My ignorance stretched to not realising it was for Mac!
