### ISSUE TITLE
Screensavers for Mac OS Silicon (Really Slick) not displaying after 1st screensaver display, then blank screen...

### ISSUE THREAD

**Issue by wmchin2003** [nickzman/microcosm#2]
Hello,

I noticed that after the screensavers display after the 1st time, the second time after that the screen goes black.  Is there a bug in the screensaver files?  I am using a Macbook Air M2 and an iMac M3.  Both have these problems.

William

**Comment by nickzman** [comment]
I can reproduce this, however, I don't think it's a bug in the screen saver module, because I can reproduce this in other screen savers as well.
